version: "3"
services:
  postgres:
    image: postgres
    expose: 
      - 5433
    ports:
      - 5433:5433
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=contracts-prod
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
  contracts-service:
    build: contracts-service/
    expose:
      - 8080
    ports:
      - 8080:8080
    command:
      - /bin/sh
      - -c
      - |
          ./gradlew task liquibase-prod update
          ./gradlew runProd
    restart: unless-stopped
    depends_on:
      - postgres
volumes:
  postgres:
