FROM openjdk:8-jdk-alpine

RUN mkdir -p /contracts-service

WORKDIR /contracts-service

COPY . /contracts-service

RUN ./gradlew build

ENTRYPOINT ["java",-jar","/contracts-web/build/libs/contracts-db-0.0.1-SNAPSHOT.jar"]
